# baseURL = "https://profile.ppqwqqq.com" # This is not used neccessarily
title = "ppQwQqq's Space"
theme = "PaperMod"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
pluralizeListTitles = false
mainSections = ["en/posts", "zh/posts"]
enableGitInfo = true
enableEmoji = true
enableInlineShortcodes = true

[params]
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowFullTextinRSS = true
showLastModified = true
dateFormat = "2006-01-01"
showWordCount = true

[params.social]
github = "ppqwqqq"

[markup]
[markup.highlight]
codeFences = true
guessSyntax = false
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = false
style = "monokai"
tabWidth = 4
anchorLineNos = true

[taxonomies]
category = "categories"
tag = "tags"

[languages]
# English Lang Site
[languages.en]
languageCode = "en-US"
languageName = "English"
weight = 1
title = "ppQwQqq's Space"
contentDir = "content/en"

[languages.en.params]
description = "ppQwQqq's Space"
author = "ppQwQqq"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true

[[languages.en.menu.main]]
identifier = "posts"
name = "Posts"
url = "posts/"
weight = 10
pageRef = "/en/posts/"

[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "about/"
weight = 20
pageRef = "/en/about/"

# Chinese Lang Site
[languages.zh]
languageCode = "zh-CN"
languageName = "中文"
weight = 2
title = "ppQwQqq 的空间"
contentDir = "content/zh"

[languages.zh.params]
description = "ppQwQqq's 的空间"
author = "ppQwQqq"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true

[[languages.zh.menu.main]]
identifier = "posts"
name = "文章"
url = "posts/"
weight = 10

[[languages.zh.menu.main]]
identifier = "about"
name = "关于"
url = "about/"
weight = 20
